#!/usr/bin/env bash
# scripts/capture-evidence.sh
# Lab 2.5 — Bundle a Terraform workspace's evidence files and upload to the
# S3 Object Lock vault with integrity hashes and a machine-readable receipt.
#
# Usage:
#   capture-evidence.sh --workspace <path> --run-id <id> --vault <bucket> [--profile <p>]
#
# Outputs (stdout):
#   Single-line JSON receipt:
#   {"run_id":"...","vault":"...","key":"...","version_id":"...","captured_at_utc":"..."}
#
# Files bundled from <workspace>:
#   plan.json   — terraform show -json tfplan (if tfplan present)
#   state.json  — terraform state pull
#   commit.txt  — git log -1 --pretty=full
#   version.txt — terraform version
#   manifest.json — per-file sha256 + size (generated by this script)

set -euo pipefail

PROFILE_ARG=""
WORKSPACE=""
RUN_ID=""
VAULT=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --workspace) WORKSPACE="$2"; shift 2 ;;
    --run-id)    RUN_ID="$2";    shift 2 ;;
    --vault)     VAULT="$2";     shift 2 ;;
    --profile)   PROFILE_ARG="--profile $2"; shift 2 ;;
    *) echo "Unknown argument: $1" >&2; exit 2 ;;
  esac
done

[[ -z "$WORKSPACE" || -z "$RUN_ID" || -z "$VAULT" ]] && {
  echo "Usage: $0 --workspace <path> --run-id <id> --vault <bucket> [--profile <p>]" >&2
  exit 2
}

# Pick sha256 tool (GNU coreutils or BSD shasum)
if command -v sha256sum >/dev/null 2>&1; then
  SHASUM="sha256sum"
elif command -v shasum >/dev/null 2>&1; then
  SHASUM="shasum -a 256"
else
  echo "ERROR: need sha256sum or shasum on PATH" >&2; exit 2
fi

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

CAPTURED_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)
BUNDLE_DIR="$WORK/bundle-$RUN_ID"
mkdir -p "$BUNDLE_DIR"

# ── Collect artefacts ──────────────────────────────────────────────────────
# plan.json: re-render from the saved tfplan if present
( cd "$WORKSPACE" && [[ -f tfplan ]] && \
    terraform show -json tfplan > "$BUNDLE_DIR/plan.json" 2>/dev/null ) || true

# state.json: current remote/local state
( cd "$WORKSPACE" && \
    terraform state pull > "$BUNDLE_DIR/state.json" 2>/dev/null ) || true

# commit.txt: last git commit in the workspace tree
( cd "$WORKSPACE" && \
    git log -1 --pretty=full > "$BUNDLE_DIR/commit.txt" 2>/dev/null ) || \
    echo "no git commit available" > "$BUNDLE_DIR/commit.txt"

# version.txt: exact terraform binary version for reproducibility
terraform version > "$BUNDLE_DIR/version.txt"

# ── Build manifest ─────────────────────────────────────────────────────────
# Per-file: filename, sha256, size (bytes), captured_at_utc
{
  echo "["
  FIRST=1
  for f in "$BUNDLE_DIR"/*; do
    base=$(basename "$f")
    [[ "$base" == "manifest.json" ]] && continue
    HASH=$($SHASUM "$f" | awk '{print $1}')
    SIZE=$(wc -c < "$f" | tr -d ' ')
    [[ $FIRST -eq 1 ]] && FIRST=0 || printf ","
    printf '\n  {"filename":"%s","sha256":"%s","size":%s,"captured_at_utc":"%s"}' \
      "$base" "$HASH" "$SIZE" "$CAPTURED_AT"
  done
  echo
  echo "]"
} > "$BUNDLE_DIR/manifest.json"

# ── Bundle + upload ────────────────────────────────────────────────────────
BUNDLE_TGZ="/tmp/bundle-${RUN_ID}.tar.gz"
( cd "$WORK" && tar czf "$BUNDLE_TGZ" "bundle-$RUN_ID" )

KEY="runs/$RUN_ID/bundle.tar.gz"

UPLOAD_OUT=$(aws $PROFILE_ARG s3api put-object \
  --bucket "$VAULT" \
  --key "$KEY" \
  --body "$BUNDLE_TGZ" \
  --output json)

VERSION_ID=$(echo "$UPLOAD_OUT" | awk -F'"' '/"VersionId"/{print $4}')

# ── JSON receipt (machine-readable, pipe-friendly) ─────────────────────────
printf '{"run_id":"%s","vault":"%s","key":"%s","version_id":"%s","captured_at_utc":"%s"}\n' \
  "$RUN_ID" "$VAULT" "$KEY" "$VERSION_ID" "$CAPTURED_AT"
